# Generated by Django 3.1 on 2020-10-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('impago', 'Impago'), ('señado', 'Señado'), ('pagado', 'Pagado')], default='impago', max_length=6),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.FileField(upload_to='transferencias/')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.reserva')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
