# Generated by Django 3.1 on 2020-09-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='carpa',
            field=models.ManyToManyField(through='backend.ReservaDetalle', to='backend.Carpa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estacionamiento',
            field=models.ManyToManyField(through='backend.ReservaDetalle', to='backend.Estacionamiento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sombrilla',
            field=models.ManyToManyField(through='backend.ReservaDetalle', to='backend.Sombrilla'),
        ),
    ]
