# Generated by Django 3.1 on 2020-10-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201009_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('carpa', 'Carpa'), ('sombrilla', 'Sombrilla'), ('estacionamiento', 'Estacionamiento')], max_length=20, unique=True)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
