# Generated by Django 3.1 on 2020-10-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadetalle',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
    ]
