# Generated by Django 3.1 on 2020-10-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_reservadetalle_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('impago', 'Impago'), ('señado', 'Señado'), ('pagado', 'Pagado'), ('procesando', 'Procesando')], default='impago', max_length=15),
        ),
    ]
